name: Deploy to ECS

on:
  push:
    branches: [ "test" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::911473676010:role/github-action-role
        aws-region: ap-south-1

    - name: debug-workflow
      run: |
        ls
        pwd

    - name: Verify AWS identity
      run: aws sts get-caller-identity

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: debug-workflow
      run: |
        aws ecr describe-repositories --region ap-south-1

    - name: Build and push Docker image
      env:
        ECR_REPO: qwerty/ecs
        IMAGE_TAG: ${{ github.sha }}
        ACCOUNT_ID: 911473676010
        REGION: ap-south-1
      run: |
        cd docker
        docker build -t $ECR_REPO:$IMAGE_TAG .
        docker tag $ECR_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
        docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
        